### ISSUE TITLE
ib.exit is not a function

### ISSUE THREAD

**Issue by grantchiu011101** [triploc/ib-sdk#3]
Hi. I got this error when i run the first example on README.md
I'm using version "^0.4.9".

```
TypeError: ib.exit is not a function
    at Environment.sdk.environment (/Users/grantchiu/dev/algo.strategies/algo.sdk/index.js:44:6)
    at Environment.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Environment.emit (events.js:191:7)
    at Accounts.loadHandler (/Users/grantchiu/dev/algo.strategies/algo.sdk/node_modules/ib-sdk/model/environment.js:55:22)
    at Accounts.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Accounts.emit (events.js:185:7)
    at Request.service.accountSummary.on.on.cancel (/Users/grantchiu/dev/algo.strategies/algo.sdk/node_modules/ib-sdk/model/accounts.js:122:18)
    at emitOne (events.js:101:20)
```

**Comment by grantchiu011101** [comment]
for the pull request i created
I can use close instance of exit function like this : 
```
ib.close (function() {
    // close callback here.
}) ;
```
